// Populates the POKEMON_KV namespace with pokemon data via wrangler CLI.
// Run with: pnpm seed
import { execSync } from 'node:child_process'
import { writeFileSync, unlinkSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const pokemon = [
  { id: 1, name: 'Bulbasaur', type: 'Grass' },
  { id: 2, name: 'Ivysaur', type: 'Grass' },
  { id: 3, name: 'Venusaur', type: 'Grass' },
  { id: 4, name: 'Charmander', type: 'Fire' },
  { id: 5, name: 'Charmeleon', type: 'Fire' },
  { id: 6, name: 'Charizard', type: 'Fire' },
  { id: 7, name: 'Squirtle', type: 'Water' },
  { id: 8, name: 'Wartortle', type: 'Water' },
  { id: 9, name: 'Blastoise', type: 'Water' },
  { id: 10, name: 'Caterpie', type: 'Bug' },
  { id: 11, name: 'Metapod', type: 'Bug' },
  { id: 12, name: 'Butterfree', type: 'Bug' },
  { id: 13, name: 'Weedle', type: 'Bug' },
  { id: 14, name: 'Kakuna', type: 'Bug' },
  { id: 15, name: 'Beedrill', type: 'Bug' },
  { id: 16, name: 'Pidgey', type: 'Normal' },
  { id: 17, name: 'Pidgeotto', type: 'Normal' },
  { id: 18, name: 'Pidgeot', type: 'Normal' },
  { id: 19, name: 'Rattata', type: 'Normal' },
  { id: 20, name: 'Raticate', type: 'Normal' },
  { id: 21, name: 'Spearow', type: 'Normal' },
  { id: 22, name: 'Fearow', type: 'Normal' },
  { id: 23, name: 'Ekans', type: 'Poison' },
  { id: 24, name: 'Arbok', type: 'Poison' },
  { id: 25, name: 'Pikachu', type: 'Electric' },
  { id: 26, name: 'Raichu', type: 'Electric' },
  { id: 27, name: 'Sandshrew', type: 'Ground' },
  { id: 28, name: 'Sandslash', type: 'Ground' },
  { id: 29, name: 'Nidoran♀', type: 'Poison' },
  { id: 30, name: 'Nidorina', type: 'Poison' },
  { id: 31, name: 'Nidoqueen', type: 'Poison' },
  { id: 32, name: 'Nidoran♂', type: 'Poison' },
  { id: 33, name: 'Nidorino', type: 'Poison' },
  { id: 34, name: 'Nidoking', type: 'Poison' },
  { id: 35, name: 'Clefairy', type: 'Fairy' },
  { id: 36, name: 'Clefable', type: 'Fairy' },
  { id: 37, name: 'Vulpix', type: 'Fire' },
  { id: 38, name: 'Ninetales', type: 'Fire' },
  { id: 39, name: 'Jigglypuff', type: 'Normal' },
  { id: 40, name: 'Wigglytuff', type: 'Normal' },
  { id: 41, name: 'Zubat', type: 'Poison' },
  { id: 42, name: 'Golbat', type: 'Poison' },
  { id: 43, name: 'Oddish', type: 'Grass' },
  { id: 44, name: 'Gloom', type: 'Grass' },
  { id: 45, name: 'Vileplume', type: 'Grass' },
  { id: 46, name: 'Paras', type: 'Bug' },
  { id: 47, name: 'Parasect', type: 'Bug' },
  { id: 48, name: 'Venonat', type: 'Bug' },
  { id: 49, name: 'Venomoth', type: 'Bug' },
  { id: 50, name: 'Diglett', type: 'Ground' },
  { id: 51, name: 'Dugtrio', type: 'Ground' },
  { id: 52, name: 'Meowth', type: 'Normal' },
  { id: 53, name: 'Persian', type: 'Normal' },
  { id: 54, name: 'Psyduck', type: 'Water' },
  { id: 55, name: 'Golduck', type: 'Water' },
  { id: 56, name: 'Mankey', type: 'Fighting' },
  { id: 57, name: 'Primeape', type: 'Fighting' },
  { id: 58, name: 'Growlithe', type: 'Fire' },
  { id: 59, name: 'Arcanine', type: 'Fire' },
  { id: 60, name: 'Poliwag', type: 'Water' },
  { id: 61, name: 'Poliwhirl', type: 'Water' },
  { id: 62, name: 'Poliwrath', type: 'Water' },
  { id: 63, name: 'Abra', type: 'Psychic' },
  { id: 64, name: 'Kadabra', type: 'Psychic' },
  { id: 65, name: 'Alakazam', type: 'Psychic' },
  { id: 66, name: 'Machop', type: 'Fighting' },
  { id: 67, name: 'Machoke', type: 'Fighting' },
  { id: 68, name: 'Machamp', type: 'Fighting' },
  { id: 69, name: 'Bellsprout', type: 'Grass' },
  { id: 70, name: 'Weepinbell', type: 'Grass' },
  { id: 71, name: 'Victreebel', type: 'Grass' },
  { id: 72, name: 'Tentacool', type: 'Water' },
  { id: 73, name: 'Tentacruel', type: 'Water' },
  { id: 74, name: 'Geodude', type: 'Rock' },
  { id: 75, name: 'Graveler', type: 'Rock' },
  { id: 76, name: 'Golem', type: 'Rock' },
  { id: 77, name: 'Ponyta', type: 'Fire' },
  { id: 78, name: 'Rapidash', type: 'Fire' },
  { id: 79, name: 'Slowpoke', type: 'Water' },
  { id: 80, name: 'Slowbro', type: 'Water' },
  { id: 81, name: 'Magnemite', type: 'Electric' },
  { id: 82, name: 'Magneton', type: 'Electric' },
  { id: 83, name: "Farfetch'd", type: 'Normal' },
  { id: 84, name: 'Doduo', type: 'Normal' },
  { id: 85, name: 'Dodrio', type: 'Normal' },
  { id: 86, name: 'Seel', type: 'Water' },
  { id: 87, name: 'Dewgong', type: 'Water' },
  { id: 88, name: 'Grimer', type: 'Poison' },
  { id: 89, name: 'Muk', type: 'Poison' },
  { id: 90, name: 'Shellder', type: 'Water' },
  { id: 91, name: 'Cloyster', type: 'Water' },
  { id: 92, name: 'Gastly', type: 'Ghost' },
  { id: 93, name: 'Haunter', type: 'Ghost' },
  { id: 94, name: 'Gengar', type: 'Ghost' },
  { id: 95, name: 'Onix', type: 'Rock' },
  { id: 96, name: 'Drowzee', type: 'Psychic' },
  { id: 97, name: 'Hypno', type: 'Psychic' },
  { id: 98, name: 'Krabby', type: 'Water' },
  { id: 99, name: 'Kingler', type: 'Water' },
  { id: 100, name: 'Voltorb', type: 'Electric' },
  { id: 101, name: 'Electrode', type: 'Electric' },
  { id: 102, name: 'Exeggcute', type: 'Grass' },
  { id: 103, name: 'Exeggutor', type: 'Grass' },
  { id: 104, name: 'Cubone', type: 'Ground' },
  { id: 105, name: 'Marowak', type: 'Ground' },
  { id: 106, name: 'Hitmonlee', type: 'Fighting' },
  { id: 107, name: 'Hitmonchan', type: 'Fighting' },
  { id: 108, name: 'Lickitung', type: 'Normal' },
  { id: 109, name: 'Koffing', type: 'Poison' },
  { id: 110, name: 'Weezing', type: 'Poison' },
  { id: 111, name: 'Rhyhorn', type: 'Ground' },
  { id: 112, name: 'Rhydon', type: 'Ground' },
  { id: 113, name: 'Chansey', type: 'Normal' },
  { id: 114, name: 'Tangela', type: 'Grass' },
  { id: 115, name: 'Kangaskhan', type: 'Normal' },
  { id: 116, name: 'Horsea', type: 'Water' },
  { id: 117, name: 'Seadra', type: 'Water' },
  { id: 118, name: 'Goldeen', type: 'Water' },
  { id: 119, name: 'Seaking', type: 'Water' },
  { id: 120, name: 'Staryu', type: 'Water' },
  { id: 121, name: 'Starmie', type: 'Water' },
  { id: 122, name: 'Mr. Mime', type: 'Psychic' },
  { id: 123, name: 'Scyther', type: 'Bug' },
  { id: 124, name: 'Jynx', type: 'Ice' },
  { id: 125, name: 'Electabuzz', type: 'Electric' },
  { id: 126, name: 'Magmar', type: 'Fire' },
  { id: 127, name: 'Pinsir', type: 'Bug' },
  { id: 128, name: 'Tauros', type: 'Normal' },
  { id: 129, name: 'Magikarp', type: 'Water' },
  { id: 130, name: 'Gyarados', type: 'Water' },
  { id: 131, name: 'Lapras', type: 'Water' },
  { id: 132, name: 'Ditto', type: 'Normal' },
  { id: 133, name: 'Eevee', type: 'Normal' },
  { id: 134, name: 'Vaporeon', type: 'Water' },
  { id: 135, name: 'Jolteon', type: 'Electric' },
  { id: 136, name: 'Flareon', type: 'Fire' },
  { id: 137, name: 'Porygon', type: 'Normal' },
  { id: 138, name: 'Omanyte', type: 'Rock' },
  { id: 139, name: 'Omastar', type: 'Rock' },
  { id: 140, name: 'Kabuto', type: 'Rock' },
  { id: 141, name: 'Kabutops', type: 'Rock' },
  { id: 142, name: 'Aerodactyl', type: 'Rock' },
  { id: 143, name: 'Snorlax', type: 'Normal' },
  { id: 144, name: 'Articuno', type: 'Ice' },
  { id: 145, name: 'Zapdos', type: 'Electric' },
  { id: 146, name: 'Moltres', type: 'Fire' },
  { id: 147, name: 'Dratini', type: 'Dragon' },
  { id: 148, name: 'Dragonair', type: 'Dragon' },
  { id: 149, name: 'Dragonite', type: 'Dragon' },
  { id: 150, name: 'Mewtwo', type: 'Psychic' },
  { id: 151, name: 'Mew', type: 'Psychic' },
]

const KV_NAMESPACE_ID = '98c49e75debc4ec4bcb616355465b47d'

const tmpFile = join(tmpdir(), 'spiceflow-kv-seed.json')

function putKv(key: string, value: string) {
  writeFileSync(tmpFile, value)
  execSync(
    `wrangler kv key put --namespace-id ${KV_NAMESPACE_ID} "${key}" --path "${tmpFile}" --remote`,
    { stdio: 'inherit' },
  )
}

console.log(`Seeding ${pokemon.length} pokemon to KV...`)

// Write all IDs index
const allIds = pokemon.map((p) => p.id)
putKv('__ids', JSON.stringify(allIds))

// Write each pokemon
for (const p of pokemon) {
  putKv(`pokemon:${p.id}`, JSON.stringify(p))
}

console.log('Done!')
