// Generates src/react/federation-flight-client-source.ts which embeds a
// pre-built copy of react-server-dom-webpack/client.browser as a string
// constant. This runs BEFORE tsc so the generated file compiles normally.
//
// The pre-built copy has two key transformations:
// 1. __webpack_require__ → globalThis.__vite_rsc_require__ (same name as
//    vite-rsc uses, so both Vite and non-Vite hosts share one global)
// 2. A require() shim backed by globalThis.__FEDERATION_MODULES__ for
//    resolving react/react-dom at module init time
import { build } from 'esbuild'
import { writeFileSync } from 'fs'
import { dirname, resolve } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outTs = resolve(__dirname, '../src/react/federation-flight-client-source.ts')

const banner = `
var require = (id) => {
  var m = globalThis.__FEDERATION_MODULES__?.[id];
  if (m) return m;
  throw new Error("[federation-flight-client] Module not found: " + id + ". Populate globalThis.__FEDERATION_MODULES__ before loading.");
};
`.trim()

const result = await build({
  stdin: {
    contents: [
      `import mod from 'react-server-dom-webpack/client.browser';`,
      `export const createFromReadableStream = mod.createFromReadableStream;`,
      `export const createFromFetch = mod.createFromFetch;`,
      `export default mod;`,
    ].join('\n'),
    resolveDir: resolve(__dirname, '..'),
    loader: 'js',
  },
  bundle: true,
  format: 'esm',
  write: false,
  external: ['react', 'react-dom'],
  platform: 'browser',
  define: {
    __webpack_require__: 'globalThis.__vite_rsc_require__',
  },
  banner: { js: banner },
  minify: false,
})

const source = result.outputFiles[0].text

const ts = [
  '// Auto-generated by scripts/build-flight-client.ts — do not edit.',
  '// Pre-built react-server-dom-webpack/client.browser with __webpack_require__',
  '// replaced by globalThis.__vite_rsc_require__ and a require() shim for React.',
  `export const FLIGHT_CLIENT_SOURCE = ${JSON.stringify(source)}`,
  '',
].join('\n')

writeFileSync(outTs, ts)
console.log(`Generated ${outTs} (${(source.length / 1024).toFixed(1)} KB)`)
