// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package no_floating_promises

import "github.com/go-json-experiment/json"
import "github.com/typescript-eslint/tsgolint/internal/utils"

type NoFloatingPromisesOptions struct {
	// AllowForKnownSafeCalls corresponds to the JSON schema field
	// "allowForKnownSafeCalls".
	AllowForKnownSafeCalls []utils.TypeOrValueSpecifier `json:"allowForKnownSafeCalls,omitempty"`

	// AllowForKnownSafePromises corresponds to the JSON schema field
	// "allowForKnownSafePromises".
	AllowForKnownSafePromises []utils.TypeOrValueSpecifier `json:"allowForKnownSafePromises,omitempty"`

	// CheckThenables corresponds to the JSON schema field "checkThenables".
	CheckThenables bool `json:"checkThenables,omitempty"`

	// IgnoreIIFE corresponds to the JSON schema field "ignoreIIFE".
	IgnoreIIFE bool `json:"ignoreIIFE,omitempty"`

	// IgnoreVoid corresponds to the JSON schema field "ignoreVoid".
	IgnoreVoid bool `json:"ignoreVoid,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *NoFloatingPromisesOptions) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain NoFloatingPromisesOptions
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if v, ok := raw["allowForKnownSafeCalls"]; !ok || v == nil {
		plain.AllowForKnownSafeCalls = []utils.TypeOrValueSpecifier{}
	}
	if v, ok := raw["allowForKnownSafePromises"]; !ok || v == nil {
		plain.AllowForKnownSafePromises = []utils.TypeOrValueSpecifier{}
	}
	if v, ok := raw["checkThenables"]; !ok || v == nil {
		plain.CheckThenables = false
	}
	if v, ok := raw["ignoreIIFE"]; !ok || v == nil {
		plain.IgnoreIIFE = false
	}
	if v, ok := raw["ignoreVoid"]; !ok || v == nil {
		plain.IgnoreVoid = true
	}
	*j = NoFloatingPromisesOptions(plain)
	return nil
}
