import { wrapGetServerSideProps as _wrapGetServerSideProps } from "server-actions-for-next-pages/dist/context-internal";
import './globals.css';
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
export default function RootLayout({
  children
}) {
  return <html lang='en'>
            <body className={'text-black bg-white'}>{children}</body>
        </html>;
}