name: CI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
  pull_request:

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - run: pnpm install --frozen-lockfile=false

      - run: pnpm build
      - run: pnpm test
      - run: pnpm --dir integration-tests exec playwright install --with-deps chromium
      - run: pnpm test-e2e
        working-directory: integration-tests
      - run: pnpm test-e2e-start
        working-directory: integration-tests
      - run: pnpm test-e2e-basepath
        working-directory: integration-tests

  deploy-example-cloudflare:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        with:
          run_install: false
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm build
        working-directory: spiceflow
      - run: pnpm build
        working-directory: example-cloudflare
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: example-cloudflare
          command: deploy
