name: CI

on:
  push:

jobs:
  ci:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
      - run: pnpm install --frozen-lockfile=false
      # scripts
      - run: pnpm build
      - run: pnpm test
